[package]
name = "sap-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "*"
nom_locate = "*"
rustyline = "9.0.0"
custom_debug_derive = "0.5.0"
custom_debug = "0.5.0"
